### ISSUE TITLE
The TODO-list screen

### ISSUE THREAD

**Issue by denistakeda** [denistakeda/LifeBalance#34]
# Requirements
- [ ] Should render the list of issues
- [ ] Should render the list of everything that been done today
- [ ] Should has ability to mark task as done
- [ ] Should have add button

**Comment by Pernach-ws** [comment]
![2017-04-07_10-17-34](https://cloud.githubusercontent.com/assets/25632878/24786508/797b9582-1b7b-11e7-9350-10a629b53424.png)
Может быть что-то типа того?
